version: "2"

linters:
  disable:
    - errcheck

  settings:
    staticcheck:
      checks:
        - all
        - -SA9003  # Empty branch - sometimes used for clarity
        - -QF1003  # Tagged switch suggestion - keep explicit for readability
        - -QF1008  # Remove embedded field from selector - keep explicit for clarity
        - -S1017   # TrimPrefix suggestion - keep explicit for readability

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
