version: "2"
linters:
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - -QF1003
        - -QF1008
        - -S1017
        - -SA9003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
