name: Writing Task
description: Content creation - emails, docs, blog posts
labels: ["type:writing", "status:queued"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - normal
        - high
        - low
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What needs to be written?
      description: Describe the content you need
      placeholder: |
        What type of content? (email, blog post, documentation, etc.)
        Who is the audience?
        What tone should it have?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Details
      description: Any additional context or requirements
      placeholder: |
        Include any relevant background, key points to cover,
        or examples of the style you want.
    validations:
      required: false
